/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tubes;

import java.awt.Color;
import static javafx.scene.paint.Color.color;

/**
 *
 * @author User
 */
public class awal extends javax.swing.JFrame {

    /**
     * Creates new form awal
     */
    public awal() {
        initComponents();
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnorder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        viewpane = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        adminnn1 = new javax.swing.JLabel();
        adminnn = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnorder.setBackground(new java.awt.Color(7, 17, 39));
        btnorder.setForeground(new java.awt.Color(204, 204, 204));
        btnorder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnorderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnorderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnorderMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("O R D E R");

        javax.swing.GroupLayout btnorderLayout = new javax.swing.GroupLayout(btnorder);
        btnorder.setLayout(btnorderLayout);
        btnorderLayout.setHorizontalGroup(
            btnorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(btnorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnorderLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );
        btnorderLayout.setVerticalGroup(
            btnorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnorderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 130, 40));

        viewpane.setBackground(new java.awt.Color(18, 18, 18));
        viewpane.setLayout(null);

        admin.setBackground(new java.awt.Color(255, 255, 255));
        admin.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("ADMIN");
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        viewpane.add(admin);
        admin.setBounds(20, 10, 130, 40);

        jPanel1.add(viewpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 150, 60));

        adminnn1.setToolTipText("");
        adminnn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminnn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminnn1MouseClicked(evt);
            }
        });
        jPanel1.add(adminnn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 504, 40, 40));

        adminnn.setToolTipText("");
        adminnn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminnn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminnnMouseClicked(evt);
            }
        });
        jPanel1.add(adminnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 504, 40, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/heyraa! (2).png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new order().setVisible(true);
    }//GEN-LAST:event_btnorderMouseClicked

    private void btnorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseEntered
        // TODO add your handling code here:
        btnorder.setBackground(new Color(20, 30, 52));
    }//GEN-LAST:event_btnorderMouseEntered

    private void btnorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMouseExited
        // TODO add your handling code here:
        btnorder.setBackground(new Color(7, 17, 39));
    }//GEN-LAST:event_btnorderMouseExited

    private void btnorderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnorderMousePressed
        // TODO add your handling code here:
        btnorder.setBackground(new Color(33, 43, 65));
    }//GEN-LAST:event_btnorderMousePressed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        
        new admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_adminMouseClicked

    private void adminnnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminnnMouseClicked
        // TODO add your handling code here:
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
        adminnn.setEnabled(false);
        adminnn.setVisible(false);
        adminnn1.setEnabled(true);
        adminnn1.setVisible(true);
    }//GEN-LAST:event_adminnnMouseClicked

    private void adminnn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminnn1MouseClicked
        // TODO add your handling code here:
        viewpane.setEnabled(true);
        viewpane.setVisible(true);
        adminnn.setEnabled(true);
        adminnn.setVisible(true);
        adminnn1.setEnabled(false);
        adminnn1.setVisible(false);
        
    
    }//GEN-LAST:event_adminnn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel adminnn;
    private javax.swing.JLabel adminnn1;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel btnorder;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel viewpane;
    // End of variables declaration//GEN-END:variables

    private void setOpacity(int i, float f) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
