
package Tubes;

import Koneksi.Koneksi;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.StringTokenizer;
import java.text.NumberFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *

 * @author ACER
 */

public class order extends javax.swing.JFrame {   
    public String menu_barang;
    public StringTokenizer token;
    public String ganti = "";
    
     double totalHarga;
     double dataTotal;
    
    DefaultTableModel model;
    DefaultTableModel dataModel;
    
    public long harga_barang;
    double  nama, harga, jmlhjual,total;
    int a=0;
    Connection con;
    Statement st;
    ResultSet rs;
    
        String qrCodeData;
	String filePath = "QRCode.png";
	String charset = "UTF-8"; 
	File imageFile =null;
    
    public order() {
        initComponents();
        Koneksi.getKoneksi();  
        tblBarang.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)tblBarang.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        tblBarang.setForeground(Color.WHITE);
        scroll.setBackground(new Color(0,0,0,0));
        scroll.setOpaque(false);
         tblBarang.setOpaque(false);
            ((DefaultTableCellRenderer)tblBarang.getDefaultRenderer(Object.class)).setOpaque(false);
        scroll.getViewport().setOpaque(false);
        tblBarang.setShowGrid(true);
        
        //input
        model = (DefaultTableModel) tblBarang.getModel();
        //remove
        model.getDataVector().removeAllElements();
        revalidate();
        kpesan();
        
        Date date = new Date(); 
        
    }
    
    public static BufferedImage loadImage(String ref){
        BufferedImage bimg =null;
        
        try {
            bimg = ImageIO.read(new File(ref));
        } catch (IOException e) {
        }
        
        return bimg;
    
    }
    
    
    private void bayar(){
            qrCodeData=txtTagihan.getText();
    }
    private void kpesan(){
       try{
            con = Koneksi.getKoneksi();
            String sql = "SELECT COUNT(kpesan) as kode FROM penjualan";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                String kode = rs.getString("kode");
                int a = Integer.parseInt(kode);
                int b = a+1;
                fkode.setText("HPK00"+b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    
    private void btnTambah(){
        
        //mengeksekusi isi tabel
        a=a+1;
        jmlhjual=Float.parseFloat(spnJumlah.getValue().toString());
        harga =Float.parseFloat(txtHarga.getText());
        total=(double)(jmlhjual*harga);
        model.insertRow(model.getRowCount(), new Object[]{String.valueOf(a),menu_barang,txtHarga.getText(),spnJumlah.getValue().toString(),String.valueOf(total)});
        
        spnJumlah.setValue(((SpinnerNumberModel) spnJumlah.getModel()).getMinimum());
        cmbBarang.setSelectedItem("Menu Pilihan");
        
        //menjumlahkan data pada kolom total(harga)
        dataModel = (DefaultTableModel) tblBarang.getModel();
        int jumlah = dataModel.getRowCount();
        totalHarga = 0;
       
        for (int i =0; i < jumlah; i++){
        dataTotal= Double.valueOf(dataModel.getValueAt(i, 4).toString());
        totalHarga += dataTotal;
//        
        //txtTagihan ke satuan rupiah
        double angka = totalHarga ;
        ganti = NumberFormat.getNumberInstance(Locale.US).format(angka);
        token = new StringTokenizer(ganti, ".");
        ganti = token.nextToken();
        ganti = ganti.replace(',', '.');
        txtTagihan.setText(String.valueOf("Rp"+ganti));
        }
        
        txtHarga.setText("");
        Float Tagihan = (float)totalHarga;
        
    
    }
    
    
    private void btnHapus(){
        a=0;
        ((DefaultTableModel)tblBarang.getModel()).setNumRows(0);
        
        
        txtTagihan.setText("");
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTagihan = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        txtHarga = new javax.swing.JTextField();
        cmbBarang = new javax.swing.JComboBox();
        spnJumlah = new javax.swing.JSpinner();
        txtTambah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTambah2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTambah3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        area = new javax.swing.JPanel();
        fkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTagihan.setBackground(new java.awt.Color(18, 18, 18));
        txtTagihan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTagihan.setForeground(new java.awt.Color(255, 255, 255));
        txtTagihan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTagihan.setToolTipText("");
        txtTagihan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255)), "Tagihan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagihanActionPerformed(evt);
            }
        });
        jPanel1.add(txtTagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 250, 90));

        scroll.setBackground(new java.awt.Color(18, 18, 18));
        scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nama Code", "Harga", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll.setViewportView(tblBarang);

        jPanel1.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 560, 147));

        txtHarga.setBackground(new java.awt.Color(18, 18, 18));
        txtHarga.setForeground(new java.awt.Color(255, 255, 255));
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 140, 30));

        cmbBarang.setBackground(new java.awt.Color(18, 18, 18));
        cmbBarang.setForeground(new java.awt.Color(255, 255, 255));
        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menu Pilihan", "Double Burger", "Pizza", "French Fries", "Ice Cola", "Caffe Latte", "Strawberry Milk" }));
        cmbBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 140, -1));

        spnJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(spnJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 80, 30));

        txtTambah.setBackground(new java.awt.Color(51, 51, 51));
        txtTambah.setForeground(new java.awt.Color(255, 255, 255));
        txtTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTambahMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("T A M B A H");

        javax.swing.GroupLayout txtTambahLayout = new javax.swing.GroupLayout(txtTambah);
        txtTambah.setLayout(txtTambahLayout);
        txtTambahLayout.setHorizontalGroup(
            txtTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(txtTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtTambahLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        txtTambahLayout.setVerticalGroup(
            txtTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(txtTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtTambahLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(txtTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 100, 30));

        txtTambah2.setBackground(new java.awt.Color(51, 51, 51));
        txtTambah2.setForeground(new java.awt.Color(255, 255, 255));
        txtTambah2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTambah2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTambah2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTambah2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTambah2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTambah2MousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("H A P U S");

        javax.swing.GroupLayout txtTambah2Layout = new javax.swing.GroupLayout(txtTambah2);
        txtTambah2.setLayout(txtTambah2Layout);
        txtTambah2Layout.setHorizontalGroup(
            txtTambah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(txtTambah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtTambah2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        txtTambah2Layout.setVerticalGroup(
            txtTambah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(txtTambah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtTambah2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(txtTambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        txtTambah3.setBackground(new java.awt.Color(51, 51, 51));
        txtTambah3.setForeground(new java.awt.Color(255, 255, 255));
        txtTambah3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTambah3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTambah3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTambah3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTambah3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTambah3MousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("O K");

        javax.swing.GroupLayout txtTambah3Layout = new javax.swing.GroupLayout(txtTambah3);
        txtTambah3.setLayout(txtTambah3Layout);
        txtTambah3Layout.setHorizontalGroup(
            txtTambah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(txtTambah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtTambah3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        txtTambah3Layout.setVerticalGroup(
            txtTambah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(txtTambah3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtTambah3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(txtTambah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        area.setBackground(new java.awt.Color(18, 18, 18));

        javax.swing.GroupLayout areaLayout = new javax.swing.GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 380, 190));

        fkode.setBackground(new java.awt.Color(18, 18, 18));
        fkode.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Pesanan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/order.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -2, 360, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void cmbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangActionPerformed
        // TODO add your handling code here:
        menu_barang = (String) cmbBarang.getSelectedItem();
        
        switch(menu_barang){
        case "Double Burger":
            txtHarga.setText(String.valueOf(" 45000"));
            break;
        case "Pizza":
            txtHarga.setText(String.valueOf("125000"));
            break;
        case "French Fries":
            txtHarga.setText(String.valueOf("  10000"));
            break;
        case "Ice Cola":
            txtHarga.setText(String.valueOf("  20000"));
            break;
        case "Caffe Latte":
            txtHarga.setText(String.valueOf(" 30000"));
            break;
        case "Strawberry Milk":
            txtHarga.setText(String.valueOf(" 25000"));
            break;
        }
      
    }//GEN-LAST:event_cmbBarangActionPerformed

    private void txtTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagihanActionPerformed

    private void txtTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMouseEntered
        // TODO add your handling code here:
        txtTambah.setBackground(new Color(64, 64, 64));
    }//GEN-LAST:event_txtTambahMouseEntered

    private void txtTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMouseExited
        // TODO add your handling code here:
        txtTambah.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_txtTambahMouseExited

    private void txtTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMousePressed
        // TODO add your handling code here:
        txtTambah.setBackground(new Color(112,112,112));
    }//GEN-LAST:event_txtTambahMousePressed

    private void txtTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambahMouseClicked
        // TODO add your handling code here:
        btnTambah();
    }//GEN-LAST:event_txtTambahMouseClicked

    private void txtTambah3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah3MouseClicked
        // TODO add your handling code here:
        try{
            con = Koneksi.getKoneksi();
            String sql = "INSERT INTO penjualan VALUES('"+fkode.getText()+"','"+ganti+"')";
            st = con.createStatement();
            st.execute(sql);
            
           
            
            
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        setVisible(false);
        new awal().setVisible(true);
    }//GEN-LAST:event_txtTambah3MouseClicked

    private void txtTambah3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah3MouseEntered
        // TODO add your handling code here:
        txtTambah3.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_txtTambah3MouseEntered

    private void txtTambah3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah3MouseExited
        // TODO add your handling code here:
        txtTambah3.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtTambah3MouseExited

    private void txtTambah3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah3MousePressed
        // TODO add your handling code here:
        txtTambah3.setBackground(new Color(112,112,112));
    }//GEN-LAST:event_txtTambah3MousePressed

    private void txtTambah2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah2MouseClicked
        // TODO add your handling code here:
        btnHapus();
    }//GEN-LAST:event_txtTambah2MouseClicked

    private void txtTambah2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah2MouseEntered
        // TODO add your handling code here:
        txtTambah2.setBackground(new Color(64, 64, 64));
    }//GEN-LAST:event_txtTambah2MouseEntered

    private void txtTambah2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah2MouseExited
        // TODO add your handling code here:
        txtTambah2.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtTambah2MouseExited

    private void txtTambah2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTambah2MousePressed
        // TODO add your handling code here:
        txtTambah2.setBackground(new Color(112,112,112));
    }//GEN-LAST:event_txtTambah2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel area;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox cmbBarang;
    private javax.swing.JTextField fkode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSpinner spnJumlah;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtTagihan;
    private javax.swing.JPanel txtTambah;
    private javax.swing.JPanel txtTambah2;
    private javax.swing.JPanel txtTambah3;
    // End of variables declaration//GEN-END:variables


}
